'''
Nanopore RNA-Seq workflow
Copyright (C) 2024, Pedro Garrido Rodríguez
'''

include: 'rules/align.smk'
include: 'rules/bambu.smk'
include: 'rules/fast5.smk'
include: 'rules/m6anet.smk'
include: 'rules/nanopolish.smk'
include: 'rules/xpore.smk'

SAMPLES = glob_wildcards(config['input_dir']+'/{sample,[^/]+}').sample

rule all:
    input:
        bamslam=expand('results/bambu/BAM/BamSlam/{sample}_data.csv', sample=SAMPLES),
        m6anet=expand('results/m6anet/inference/{sample}', sample=SAMPLES),
        xpore='results/xpore/diffmod'