# Nanopore RNA-Seq workflow
# Copyright (C) 2024, Pedro Garrido Rodríguez

input_dir: '../input'
out_dir: 'results'
ref: '../hg38'
ref_tx: '../gencode.v45.annotation.gtf.gz'
xpore_diffmod: '../diffmod.yml'
sqanti_dir: '/opt/SQANTI3-5.2.2'